#!/bin/sh
set -e

PACKAGE_VERSION=3.2.21

make dist-xz
cp fs-uae-arcade-$PACKAGE_VERSION.tar.xz fs-uae-arcade_$PACKAGE_VERSION.orig.tar.xz

make distdir
cd fs-uae-arcade-$PACKAGE_VERSION
dpkg-buildpackage -S -us -uc

cd ..

OBS_PROJECT="home:FrodeSolheim"
OBS_PACKAGE_DIR=~/obs/"$OBS_PROJECT"/fs-uae-arcade

rm -f "$OBS_PACKAGE_DIR"/*
cp fs-uae-arcade_$PACKAGE_VERSION-0.debian.tar.xz "$OBS_PACKAGE_DIR"/
cp fs-uae-arcade_$PACKAGE_VERSION-0.dsc "$OBS_PACKAGE_DIR"/
cp fs-uae-arcade_$PACKAGE_VERSION.orig.tar.xz "$OBS_PACKAGE_DIR"/

cp fs-uae-arcade.spec "$OBS_PACKAGE_DIR"/

echo "Now you can:"
echo ""
echo "cd \"$OBS_PACKAGE_DIR\""
echo "osc addremove . && EDITOR=nano osc commit -m Updated"
echo ""
